# Generated by Django 2.2.17 on 2020-11-20 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0002_auto_20201120_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivos', models.TextField(blank=True, max_length=250)),
                ('resumo', models.TextField(blank=True, max_length=600)),
                ('cursos_complementares', models.TextField(blank=True, max_length=500)),
                ('info_complementares', models.TextField(blank=True, max_length=500)),
                ('user_curriculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Historico_Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.TextField(blank=True, max_length=250)),
                ('duracao_meses', models.IntegerField(blank=True)),
                ('atribuicoes', models.TextField(blank=True, max_length=250)),
                ('nome_cargo', models.TextField(blank=True, max_length=250)),
                ('hist_curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculos.Curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_formacao', models.TextField(blank=True, max_length=250)),
                ('nome_instituicao', models.TextField(blank=True, max_length=250)),
                ('duracao_meses', models.TextField(blank=True, max_length=250)),
                ('tipo_formacao', models.CharField(blank=True, choices=[('FUN', 'FUNDAMENTAL'), ('MED', 'MEDIO'), ('ESP', 'ESPECIALIZACAO'), ('MBA', 'MBA'), ('MES', 'MESTRADO'), ('DOU', 'DOUTORADO')], default='', max_length=3)),
                ('situacao_atual', models.CharField(blank=True, choices=[('FUN', 'FUNDAMENTAL'), ('MED', 'MEDIO'), ('ESP', 'ESPECIALIZACAO'), ('MBA', 'MBA'), ('MES', 'MESTRADO'), ('DOU', 'DOUTORADO')], default='', max_length=3)),
                ('form_curriculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculos.Curriculo')),
            ],
        ),
    ]
