# Generated by Django 2.2.17 on 2020-11-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='duracao_meses',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='formacao',
            name='form_curriculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa'),
        ),
        migrations.AlterField(
            model_name='historico_profissional',
            name='hist_curriculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.Pessoa'),
        ),
    ]
