# Generated by Django 2.2.17 on 2020-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_auto_20201120_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
