# Generated by Django 2.2.17 on 2020-11-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_auto_20201120_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='nome_empresa',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
