# Generated by Django 2.2.17 on 2020-11-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_auto_20201120_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='filme_relacionado',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
